import dotenv from 'dotenv';

dotenv.config();
dotenv.config({ path: 'error.env' });

const ENVIRONMENT = {
  port: process.env.PORT,
  databaseUrl: process.env.DATABASE_URL,
  jwtSecret: process.env.JWT_SECRET || 'defaultsecret',
  apiUrl: process.env.API_URL,
  host: process.env.HOST,
};

const ERROR_ENVIRONMENT = {
  RESULTS_NOT_FOUND: process.env.RESULTS_NOT_FOUND,
  INVALID_TOKEN: process.env.INVALID_TOKEN,
  EMAIL_EXISTS: process.env.EMAIL_EXISTS,
  EMAIL_NOT_FOUND: process.env.EMAIL_NOT_FOUND,
  EMAIL_FORMAT_ERROR: process.env.EMAIL_FORMAT_ERROR,
  INSERTION_FAILED: process.env.INSERTION_FAILED,
  DELETION_FAILED: process.env.DELETION_FAILED,
  UPDATE_FAILED: process.env.UPDATE_FAILED,
  MISSING_PARAMETERS: process.env.MISSING_PARAMETERS,
  DB_CONNECTION_FAILED: process.env.DB_CONNECTION_FAILED,
  FORM_VALIDATION_FAILED: process.env.FORM_VALIDATION_FAILED,
  INSUFFICIENT_PERMISSIONS: process.env.INSUFFICIENT_PERMISSIONS,
  INTERNAL_SERVER_ERROR: process.env.INTERNAL_SERVER_ERROR,
  REQUEST_TIMEOUT: process.env.REQUEST_TIMEOUT,
  INVALID_FILE_FORMAT: process.env.INVALID_FILE_FORMAT,
  AUTHENTICATION_FAILED: process.env.AUTHENTICATION_FAILED,
  DUPLICATE_DATA: process.env.DUPLICATE_DATA,
  SERVER_CONFIGURATION_ERROR: process.env.SERVER_CONFIGURATION_ERROR,
  SIZE_LIMIT_EXCEEDED: process.env.SIZE_LIMIT_EXCEEDED,
  INVALID_REQUEST: process.env.INVALID_REQUEST,
  TEMPORARY_UNAVAILABLE: process.env.TEMPORARY_UNAVAILABLE,
  INVALID_TOKEN_DECODE: process.env.INVALID_TOKEN_DECODE,
  DNI_EXISTS: process.env.DNI_EXISTS,
  DNI_NOT_FOUND: process.env.DNI_NOT_FOUND,
  INVALID_REQUEST_PREPARATION: process.env.INVALID_REQUEST_PREPARATION,
  INVALID_LOGIN_REQUEST: process.env.INVALID_LOGIN_REQUEST,
  INVALID_EMAIL_REQUEST_VERIFICATION: process.env.INVALID_EMAIL_REQUEST_VERIFICATION,
  ERROR_GENERATING_TOKEN: process.env.ERROR_GENERATING_TOKEN,
};

export {ENVIRONMENT, ERROR_ENVIRONMENT};
